# Generated by Django 5.1.5 on 2025-01-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_curso_turma_remove_aluno_curso_aluno_cursos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='cadastro.curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
