# Generated by Django 4.2.7 on 2025-02-08 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('mensalista', 'Mensalista'), ('avulso', 'Avulso')], default='avulso', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEstacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_carro', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('hora_entrada', models.TimeField(auto_now_add=True)),
                ('hora_saida', models.TimeField(blank=True, null=True)),
                ('status_pagamento', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'A pagar')], default='pendente', max_length=10)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
    ]
