# Generated by Django 5.1.5 on 2025-02-12 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='modelo_carro',
            new_name='modelo',
        ),
    ]
