# Generated by Django 5.1.5 on 2025-01-27 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.contacorrente'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='operacao',
            field=models.CharField(max_length=20),
        ),
    ]
