# Generated by Django 5.1.5 on 2025-01-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_alter_historico_conta_alter_historico_operacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='tipo',
            field=models.CharField(default='Crédito', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historico',
            name='operacao',
            field=models.CharField(max_length=50),
        ),
    ]
