# Generated by Django 5.1.5 on 2025-01-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_historico_tipo_alter_historico_operacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historico',
            name='tipo',
            field=models.CharField(default='Crédito', max_length=50),
        ),
    ]
